In [1]:
import numpy as np

A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12]]) # 8x + 3y - 2z = 9, ...
b = np.array([9, 15, 35])
x = np.linalg.solve(A, b)
x

array([-0.58226371,  3.22870478, -1.98599767])

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
n = pd.read_csv('2_T.csv', index_col='cm')
e = pd.read_csv('2_E.csv', index_col='cm')
s = pd.read_csv('2_B.csv', index_col='cm')
w = pd.read_csv('2_W.csv', index_col='cm')
w.head()

W2      W1       C      E1      E2
cm                                          
4.00  751659  751617  758056  752481  750970
5.00  751455  751604  758621  753211  751638
5.25  751488  751700  758792  753395  751804
5.50  751542  751856  759008  753605  751994
5.75  751644  752061  759252  753838  752185

In [15]:
w.index

Index([4.0, 5.0, 5.25, 5.5, 5.75, 6.0, 7.0, 8.0, 9.0, 10.0, 10.7], dtype='float64', name='cm')

In [9]:
rhs = np.concatenate((np.array(n.values.tolist()).flatten(),np.array(e.values.tolist()).flatten(),np.array(s.values.tolist()).flatten(),np.array(w.values.tolist()).flatten()))
rhs

array([739345, 751792, 750023, 751446, 748255, 748981, 751604, 749901,
       751953, 749346, 748961, 751632, 749929, 752139, 749573, 748956,
       751790, 750130, 752689, 750453, 748961, 751792, 750131, 752691,
       750455, 749036, 751941, 750297, 752995, 750841, 748442, 751618,
       750169, 753700, 752079, 748392, 751716, 750543, 754956, 753913,
       748247, 751701, 750800, 756199, 755962, 748104, 751738, 751174,
       757559, 758341, 747140, 750798, 750352, 757325, 758926, 745448,
       752241, 746886, 753332, 749444, 745503, 752213, 746785, 753805,
       750951, 745517, 752235, 746809, 754001, 751322, 745524, 752255,
       746866, 754224, 751745, 745585, 752320, 746989, 754491, 752145,
       745669, 752415, 747119, 754761, 752538, 744943, 751957, 746886,
       755192, 753531, 744512, 751922, 747167, 755985, 754944, 743944,
       751757, 747357, 756794, 756559, 743298, 751673, 747845, 758182,
       758822, 742010, 750734, 747273, 758217, 759457, 754363, 751035,
      

In [12]:
np.concatenate((np.identity(3), np.identity(3)), axis=1)

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])

In [14]:
N = np.concatenate((np.identity(55), np.identity(55)), axis=1)

In [ ]:
temp = np.zeros((55,55))
for i in range(1,6):
    for j in range(1,6):
        

In [16]:
center = np.array([751174, 747845, 757341, 759769])
print(np.mean(center), np.std(center))

754032.25 4751.572969817469


In [18]:
error = center - np.mean(center)
error

array([-2858.25, -6187.25,  3308.75,  5736.75])

In [21]:
temp = np.zeros((7,9))
temp

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
temp[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
# fill the temp
for i in range(7): # iterrows
    if i in [0,2,6]:
        temp[i] = [1,0,1,0,0,0,1,0,1] #w1, w3, w7, w9
    elif i in [1,3,5]:
        temp[i] = [0,1,0,1,0,1,0,1,0] #2,4,6,8
    else:
        temp[i] = [0,0,0,0,1,0,0,0,0]
temp = np.array(temp)

In [28]:
top = np.concatenate((np.identity(7), temp), axis=1)
top

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.]])

In [66]:
temp2 = np.zeros((9,7))
temp2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [67]:
for i in range(9):
    if i in [0,2,6,8]:
        temp2[i] = [1,0,1,0,0,0,1] #1,3,7
    elif i in [1,3,4,7]:
        temp2[i] = [0,1,0,1,0,1,0] #2,4,6
temp2 

array([[1., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 1.]])

In [68]:
bottom = np.concatenate((temp2,np.identity(9)), axis=1)
bottom

array([[1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
# bottom = np.delete(bottom, 5, axis=0)
# bottom

array([[1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [80]:
A = np.concatenate((top, bottom), axis=0)
center = 754032
b = np.array([3009664, 3012046, 2984495, 3009826, center, 3027679, 3030850, 
              2260436, 2260876, 2251648, 2254581, center, 2271091, 2257899, 2263003, 2255026])

In [81]:
np.linalg.solve(A, b)

array([ 5.48297909e+05,  7.49658250e+05,  5.23128909e+05,  7.47438250e+05,
        2.26238775e+06,  7.65291250e+05,  5.69483909e+05,  6.19525273e+05,
       -1.51175000e+03,  6.10737273e+05, -7.80675000e+03, -1.50835575e+06,
        2.27109100e+06,  6.16988273e+05,  6.15250000e+02,  6.14115273e+05])

In [93]:
x = np.linalg.solve(A, b)

def detectSign(arr):
    flag = 1
    for i in arr:
        if i < 0:
            flag *= -1
    if flag==1:
        return True
    else:
        return False

detectSign(x)

False

In [101]:
# change the center value to find a set of positive solutions
signs = []
for i in np.linspace(754032-6187.25, 754032+6187.25+1, 500):
    center = i
    b = np.array([3009664, 3012046, 2984495, 3009826, center, 3027679, 3030850, 
              2260436, 2260876, 2251648, 2254581, center, 2271091, 2257899, 2263003, 2255026])
    x = np.linalg.solve(A, b)
    signs.append(detectSign(x))
np.any(signs)

False

In [ ]:
# change values within the error range to find a set of positive solutions
signs = []
error = 6187.25
b = np.array([3009664, 3012046, 2984495, 3009826, 754032, 3027679, 3030850, 
              2260436, 2260876, 2251648, 2254581, 754032, 2271091, 2257899, 2263003, 2255026])

for i0 in np.linspace(b[0]-error, b[0]+error, 5):
    for i1 in np.linspace(b[1]-error, b[1]+error, 5):
        for i2 in np.linspace(b[2]-error, b[2]+error, 5):
            for i3 in np.linspace(b[3]-error, b[3]+error, 5):
                for i4 in np.linspace(b[4]-error, b[4]+error, 5): # center
                    for i5 in np.linspace(b[5]-error, b[5]+error, 5):
                        for i6 in np.linspace(b[6]-error, b[6]+error, 5):
                            for i7 in np.linspace(b[7]-error, b[7]+error, 5):
                                for i8 in np.linspace(b[8]-error, b[8]+error, 5):
                                    for i9 in np.linspace(b[9]-error, b[9]+error, 5):
                                        for i10 in np.linspace(b[10]-error, b[10]+error, 5):
                                            for i11 in np.linspace(b[11]-error, b[11]+error, 5):
                                                for i12 in np.linspace(b[12]-error, b[12]+error, 5):
                                                    for i13 in np.linspace(b[13]-error, b[13]+error, 5):
                                                        for i14 in np.linspace(b[14]-error, b[14]+error, 5):
                                                            b = np.array([i0, i1, i2, i3, i4, i5, i6, 
                                                                      i7, i8, i9, i10, i4, i11, i12, i13, i14])
                                                            x = np.linalg.solve(A, b)
                                                            signs.append(detectSign(x))
np.any(signs)